# See the writing guide of rbs: https://github.com/ruby/rbs#guides

module MarkdownPDF
  VERSION: String

  class Generator
    def initialize: (?fonts_path: String fp, ?styling_image_path: String sip, ?styling_yml_filename: String syf) -> void

    def file_to_pdf: (markdown_file: String, pdf_destination_file: String, images_path: String | nil) -> void

    def file_to_pdf_bin: (markdown_file: String, images_path: String | nil) -> String

    def markdown_to_pdf: (markdown_string: String, pdf_destination_file: String, images_path: String | nil) -> void

    def markdown_to_pdf_bin: (markdown_string: String, images_path: String | nil) -> String
  end

  def render_markdown: (markdown_file: String, styling_yml_filename: String, images_path: String) -> String

  def render_markdown_string: (markdown_string: String, styling_yml_filename: String, images_path: String) -> String

  def generate_markdown_pdf: (markdown_file: String, styling_yml_filename: String, pdf_destination_file: String) -> void

  def generate_markdown_string_pdf: (markdown_string: String, styling_yml_filename: String, images_path: String, pdf_destination_file: String) -> void
end
